#!/bin/bash

set -e

# read in from .env file
if [ -f $SNAP_DATA/src/envfile ]; then
  echo "Loading environment variables from $SNAP_DATA/envfile"
  export $(cat $SNAP_DATA/src/envfile | xargs)
else
  echo "No .env file found in $SNAP_DATA/src"
  exit 1;
fi

cd $SNAP_DATA/src && $SNAP/bin/python3 $SNAP_DATA/swirl_load.py
